name = "Loom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Loom", "CaseStudies"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "auto"
scope = "leanprover-community"
rev = "2c088e7617d6e2018386de23b5df3b127fae4634"

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl"
rev = "8e951c49f202d47dba756cfffe8b918aedf1ea71"

[[lean_lib]]
name = "Loom"

[[lean_lib]]
name = "CaseStudies"

