name = "Loom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Loom", "Velvet"]

[[lean_lib]]
name = "Velvet"
srcDir = "Velvet"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0"

[[require]]
name = "auto"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "Loom"
